export const SEARCH_WIKI_REQUEST = 'SEARCH_WIKI_REQUEST'
export const SEARCH_WIKI_SUCCESS = 'SEARCH_WIKI_SUCCESS'
export const SEARCH_WIKI_FAILURE = 'SEARCH_WIKI_FAILURE'
export const SET_QUERY = 'SET_QUERY'